/** Relative to axios baseURL `/api` */
export const API_ENDPOINTS = {
  // Wiki / Vault
  WIKI_CAPTURE: '/wiki/capture',
  WIKI_SOURCES: '/wiki/sources',
  wikiSource: (id: number) => `/wiki/sources/${id}`,
  WIKI_INDEX: '/wiki/index',
  WIKI_PAGE: '/wiki/page',
  WIKI_RECENT: '/wiki/recent',
  WIKI_LOG: '/wiki/log',
  WIKI_GRAPH: '/wiki/graph',
  WIKI_STATS: '/wiki/stats',
  wikiCompile: (id: number) => `/wiki/compile/${id}`,
  WIKI_COMPILE_BATCH: '/wiki/compile/batch',
  WIKI_LINT: '/wiki/lint',
  WIKI_SEARCH: '/wiki/search',
  WIKI_SEARCH_AI: '/wiki/search/ai',
  WIKI_SEARCH_AI_FILE: '/wiki/search/ai/file',
  WIKI_SYNC: '/wiki/sync',
  WIKI_AGENT_STATUS: '/wiki/agent/status',
  WIKI_AGENT_PROFILES: '/wiki/agent/profiles',
  wikiAgentProfile: (id: number) => `/wiki/agent/profiles/${id}`,
  wikiAgentSetDefault: (id: number) => `/wiki/agent/profiles/${id}/set-default`,
  wikiAgentTest: (id: number) => `/wiki/agent/profiles/${id}/test`,
  SCHEDULE: '/schedule',
  SCHEDULE_NOW: '/schedule/now',
  HABITS_TODAY: '/habits/today',
  habitCheck: (id: number) => `/habits/${id}/check`,
  VAPID_PUBLIC_KEY: '/notifications/vapid-public-key',
  NOTIFICATION_SUBSCRIBE: '/notifications/subscribe',
  NOTIFICATION_UNSUBSCRIBE: '/notifications/unsubscribe',
  NOTIFICATION_PREFERENCES: '/notifications/preferences',
  NOTIFICATION_TEST: '/notifications/test',
  FOCUS_START: '/focus/start',
  FOCUS_STOP: '/focus/stop',
  FOCUS_CURRENT: '/focus/current',
  FOCUS_HISTORY: '/focus/history',
  BLOCKED_SITES: '/blocked-sites',
  blockedSiteDelete: (id: number) => `/blocked-sites/${id}`,
  blockedSiteToggle: (id: number) => `/blocked-sites/${id}/toggle`,
  REVIEW: '/review',
  reviewByDate: (date: string) => `/review/${date}`,
  REVIEW_CALENDAR: '/review/calendar',
  REVIEW_SEARCH: '/review/search',
  REVIEW_WEEKLY: '/review/weekly',
  scheduleDay: (day: string) => `/schedule/${day}`,
  SCHEDULE_DUPLICATE: '/schedule/duplicate',
  XP: '/xp',
  ACTIVITY_SUMMARY: '/activity/summary',
  ACTIVITY_LABELS: '/activity/labels',
  ACTIVITY_TRAIN: '/activity/train',
  ACTIVITY_MODEL_STATUS: '/activity/model/status',
} as const
