/** Relative to axios baseURL `/api` */
export const API_ENDPOINTS = {
  SCHEDULE: '/schedule',
  SCHEDULE_NOW: '/schedule/now',
  HABITS_TODAY: '/habits/today',
  habitCheck: (id: number) => `/habits/${id}/check`,
  VAPID_PUBLIC_KEY: '/notifications/vapid-public-key',
  NOTIFICATION_SUBSCRIBE: '/notifications/subscribe',
  NOTIFICATION_UNSUBSCRIBE: '/notifications/unsubscribe',
  NOTIFICATION_PREFERENCES: '/notifications/preferences',
  NOTIFICATION_TEST: '/notifications/test',
  FOCUS_START: '/focus/start',
  FOCUS_STOP: '/focus/stop',
  FOCUS_CURRENT: '/focus/current',
  FOCUS_HISTORY: '/focus/history',
  BLOCKED_SITES: '/blocked-sites',
  blockedSiteDelete: (id: number) => `/blocked-sites/${id}`,
  blockedSiteToggle: (id: number) => `/blocked-sites/${id}/toggle`,
  REVIEW: '/review',
  reviewByDate: (date: string) => `/review/${date}`,
  REVIEW_CALENDAR: '/review/calendar',
  REVIEW_SEARCH: '/review/search',
  REVIEW_WEEKLY: '/review/weekly',
  scheduleDay: (day: string) => `/schedule/${day}`,
  SCHEDULE_DUPLICATE: '/schedule/duplicate',
  XP: '/xp',
} as const
