// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Protocol.Api.Data;

#nullable disable

namespace Protocol.Api.Data.Migrations
{
    [DbContext(typeof(ProtocolDbContext))]
    [Migration("20260423000001_AddWebsiteActivity")]
    partial class AddWebsiteActivity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("Protocol.Api.Models.WebsiteMlTrainingRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DistractingCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("NeutralCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductiveCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainingExampleCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("WebsiteMlTrainingRuns");
                });

            modelBuilder.Entity("Protocol.Api.Models.WebsiteProductivityLabel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Domain");

                    b.HasIndex("Scope", "Target")
                        .IsUnique();

                    b.ToTable("WebsiteProductivityLabels");
                });

            modelBuilder.Entity("Protocol.Api.Models.WebsiteVisitSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PredictedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<float?>("PredictionConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("ProductivityLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceBrowser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Domain");

                    b.HasIndex("ProductivityLabel");

                    b.HasIndex("SessionKey")
                        .IsUnique();

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("WebsiteVisitSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
