// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Protocol.Api.Data;

#nullable disable

namespace Protocol.Api.Data.Migrations
{
    [DbContext(typeof(ProtocolDbContext))]
    [Migration("20260422000001_AddWikiAgentProfiles")]
    partial class AddWikiAgentProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");
#pragma warning restore 612, 618
        }
    }
}
